import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    backgroundColor: "#fff",
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    minHeight: 40,
  },
  logo: {
    fontSize: 26,
    fontWeight: "600",
    color: "#000",
  },
  logoAccent: {
    color: "#D4A574",
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 25,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#000",
    padding: 0,
  },
  filterContainer: {
    marginBottom: 3,
  },
  filterContentContainer: {
    paddingRight: 20,
  },
  filterButton: {
    backgroundColor: "#333",
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
  },
  filterText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  feed: {
    flex: 1,
  },
  post: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#333",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  userDetails: {
    flex: 1,
  },
  userHeader: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  username: {
    fontSize: 14,
    fontWeight: "500",
    color: "#000",
  },
  rankedText: {
    fontSize: 14,
    color: "#666",
  },
  restaurant: {
    fontSize: 14,
    fontWeight: "700",
    color: "#000",
  },
  metadata: {
    marginTop: 4,
  },
  metadataRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  metadataText: {
    fontSize: 12,
    color: "#666",
  },
  imagesContainer: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  imageWrapper: {
    flex: 1,
    position: "relative",
  },
  singleImageWrapper: {
    flex: 0,
    width: 208,
  },
  foodImage: {
    width: "100%",
    height: 224,
    borderRadius: 12,
  },
  rating: {
    position: "absolute",
    bottom: 8,
    right: 8,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 2,
  },
  ratingText: {
    fontWeight: "700",
    fontSize: 14,
    color: "#000",
  },
  menuItemsContainer: {
    backgroundColor: "#f8f8f8",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    minHeight: 120,
  },
  menuItemsHeader: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 12,
  },
  menuItemWrapper: {
    marginBottom: 6,
  },
  menuItemText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
  },
  mealRatingWrapper: {
    alignItems: "flex-end",
    marginTop: 12,
  },
  mealRating: {
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 2,
  },
  noContentContainer: {
    backgroundColor: "#f0f0f0",
    borderRadius: 12,
    padding: 24,
    alignItems: "center",
    marginBottom: 12,
  },
  noContentText: {
    fontSize: 14,
    color: "#999",
    fontStyle: "italic",
  },
  notesContainer: {
    marginBottom: 12,
  },
  notesText: {
    fontSize: 14,
    color: "#000",
  },
  notesLabel: {
    fontWeight: "600",
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 3,
  },
  actionsLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  actionsRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  socialStats: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  likesText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
    marginBottom: 4,
  },
  commentsText: {
    fontSize: 14,
    color: "#666",
  },
  filledHeart: {
    fontSize: 24,
    color: "#e91e63",
  },
  // Comments Modal Styles
  commentsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    backgroundColor: "#fff",
  },
  commentsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000",
  },
  commentsList: {
    flex: 1,
    backgroundColor: "#fff",
  },
  loadingText: {
    textAlign: "center",
    color: "#666",
    fontSize: 16,
    marginTop: 50,
  },
  noCommentsText: {
    textAlign: "center",
    color: "#666",
    fontSize: 16,
    marginTop: 50,
    paddingHorizontal: 20,
  },
  commentItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f8f8f8",
  },
  commentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  commentUsername: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
  },
  commentDate: {
    fontSize: 12,
    color: "#666",
  },
  commentText: {
    fontSize: 14,
    color: "#000",
    lineHeight: 20,
  },
  addCommentContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    backgroundColor: "#fff",
  },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    fontSize: 16,
    maxHeight: 100,
    marginRight: 12,
  },
  submitCommentButton: {
    padding: 8,
  },
  submitCommentButtonDisabled: {
    opacity: 0.5,
  },
  submitCommentButtonText: {
    color: "#007AFF",
    fontSize: 16,
  },
  bottomNav: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
  },
  navLabel: {
    fontSize: 11,
    marginTop: 4,
    color: "#999",
  },
  navLabelActive: {
    color: "#000",
    fontWeight: "600",
  },
  menusContainer: {
    padding: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#000",
    marginBottom: 16,
  },
  facilityCard: {
    backgroundColor: "#D4A574",
    borderRadius: 12,
    padding: 20,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  facilityName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
    flex: 1,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    minWidth: 70,
    alignItems: "center",
  },
  statusOpen: {
    backgroundColor: "#10B981",
  },
  statusClosed: {
    backgroundColor: "#EF4444",
  },
  statusText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  diningHallHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  backButton: {
    marginRight: 12,
  },
  diningHallTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#000",
  },
  menuList: {
    flex: 1,
    paddingHorizontal: 20,
  },
  daySection: {
    marginTop: 24,
    marginBottom: 8,
  },
  dayHeader: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000",
    marginBottom: 12,
  },
  mealButton: {
    paddingVertical: 12,
    marginBottom: 8,
  },
  mealText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#D4A574",
  },
  // Search Page Styles
  searchContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  searchTabs: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  searchTab: {
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginRight: 12,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  searchTabActive: {
    borderBottomColor: "#D4A574",
  },
  searchTabText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#999",
  },
  searchTabTextActive: {
    color: "#000",
  },
  searchResults: {
    flex: 1,
    paddingHorizontal: 20,
  },
  searchResultItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
    marginBottom: 4,
  },
  searchResultSubtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
  },
  searchResultFrequency: {
    fontSize: 12,
    color: "#999",
    fontStyle: "italic",
  },
  emptySearchState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptySearchTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 8,
  },
  emptySearchText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    paddingHorizontal: 20,
  },
  searchLoading: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  // Search Results Dropdown/Modal Styles
  searchResultsOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "flex-start",
  },
  searchResultsDropdown: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginVertical: 60,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    maxHeight: 400,
  },
  searchResultDropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  searchResultDropdownName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000",
    marginBottom: 2,
  },
  searchResultDropdownSubtitle: {
    fontSize: 13,
    color: "#666",
  },
  searchResultsLoadingContainer: {
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  searchResultsEmptyContainer: {
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  searchResultsEmptyText: {
    fontSize: 14,
    color: "#999",
    fontStyle: "italic",
  },
  // Trending Page Styles
  trendingHeader: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: "#fff",
  },
  trendingTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#000",
    marginBottom: 4,
  },
  trendingSubtitle: {
    fontSize: 14,
    color: "#666",
  },
  trendingDishItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  trendingRankBadge: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  trendingRankEmoji: {
    fontSize: 20,
  },
  trendingRankText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#fff",
  },
  trendingDishName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
    marginBottom: 6,
  },
  trendingDishStats: {
    flexDirection: "row",
    alignItems: "center",
  },
  trendingDishFrequency: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  trendingTrendIndicator: {
    marginLeft: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  trendingEmptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    paddingHorizontal: 20,
  },
  trendingEmptyTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 8,
  },
  trendingEmptyText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    marginBottom: 20,
  },
  trendingRetryButton: {
    backgroundColor: "#D4A574",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 12,
  },
  trendingRetryText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },
});

export default styles;
